CREATE TABLE IF NOT EXISTS messages (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  text TEXT NOT NULL,
  author TEXT NOT NULL,
  time TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS gallery (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  src TEXT NOT NULL,
  title TEXT DEFAULT 'Memory',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS admin (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  password_hash TEXT NOT NULL
);

DELETE FROM admin;
INSERT INTO admin (password_hash) 
VALUES ('$2a$10$T8Z6mZ.N6yWjG8jZ5Yjdu7jB9G/N2uUvP2Xm8z8p2Xm8z8p2Xm8z');
